CREATE TABLE IF NOT EXISTS `ta_import_pns` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `file_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pns_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nip_baru` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nip_lama` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gelar_depan` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gelar_belakang` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tempat_lahir` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tempat_lahir_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tanggal_lahir` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jenis_kelamin` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `agama_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `agama_nama` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jenis_kawin_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jenis_kawin_nama` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nik` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nomor_hp` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email_gov` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `alamat` text COLLATE utf8mb4_unicode_ci,
  `npwp_nomor` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bpjs` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jenis_pegawai_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jenis_pegawai_nama` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kedudukan_pns_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kedudukan_pns_nama` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status_cpns_pns` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kartu_asn_virtual` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nomor_sk_cpns` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tanggal_sk_cpns` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tmt_cpns` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nomor_sk_pns` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tanggal_sk_pns` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tmt_pns` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gol_awal_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gol_awal_nama` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gol_akhir_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gol_akhir_nama` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tmt_golongan` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mk_tahun` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mk_bulan` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jenis_jabatan_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jenis_jabatan_nama` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jabatan_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jabatan_nama` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tmt_jabatan` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tingkat_pendidikan_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tingkat_pendidikan_nama` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pendidikan_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pendidikan_nama` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tahun_lulus` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kpkn_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kpkn_nama` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lokasi_kerja_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lokasi_kerja_nama` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unor_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unor_nama` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `instansi_induk_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `instansi_induk_nama` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `instansi_kerja_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `instansi_kerja_nama` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `satuan_kerja_induk_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `satuan_kerja_induk_nama` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `satuan_kerja_kerja_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `satuan_kerja_kerja_nama` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_valid_nik` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_sekolah` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `flag_ikd` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `csv_created_at` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `csv_updated_at` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `eselon_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `eselon_nama` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_ta_import_pns_nip_baru` (`nip_baru`),
  KEY `idx_ta_import_pns_pns_id` (`pns_id`),
  KEY `idx_ta_import_pns_nik` (`nik`),
  KEY `idx_ta_import_pns_batch_id` (`batch_id`),
  KEY `idx_ta_import_pns_unor_id` (`unor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
