CREATE TABLE IF NOT EXISTS `ta_import_pns` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch_id` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `file_name` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pns_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nip_baru` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nip_lama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gelar_depan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gelar_belakang` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tempat_lahir` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tempat_lahir_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tanggal_lahir` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jenis_kelamin` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `agama_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `agama_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jenis_kawin_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jenis_kawin_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nik` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nomor_hp` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email_gov` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `alamat` text COLLATE utf8mb4_unicode_ci,
  `npwp_nomor` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bpjs` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jenis_pegawai_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jenis_pegawai_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kedudukan_pns_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kedudukan_pns_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status_cpns_pns` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kartu_asn_virtual` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nomor_sk_cpns` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tanggal_sk_cpns` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tmt_cpns` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nomor_sk_pns` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tanggal_sk_pns` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tmt_pns` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gol_awal_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gol_awal_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gol_akhir_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `gol_akhir_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tmt_golongan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mk_tahun` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mk_bulan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jenis_jabatan_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jenis_jabatan_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jabatan_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `jabatan_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tmt_jabatan` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tingkat_pendidikan_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tingkat_pendidikan_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pendidikan_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pendidikan_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tahun_lulus` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kpkn_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `kpkn_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lokasi_kerja_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lokasi_kerja_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unor_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unor_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `instansi_induk_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `instansi_induk_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `instansi_kerja_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `instansi_kerja_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `satuan_kerja_induk_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `satuan_kerja_induk_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `satuan_kerja_kerja_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `satuan_kerja_kerja_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_valid_nik` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nama_sekolah` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `flag_ikd` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `csv_created_at` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `csv_updated_at` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `eselon_id` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `eselon_nama` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_ta_import_pns_nip_baru` (`nip_baru`),
  KEY `idx_ta_import_pns_pns_id` (`pns_id`),
  KEY `idx_ta_import_pns_nik` (`nik`),
  KEY `idx_ta_import_pns_batch_id` (`batch_id`),
  KEY `idx_ta_import_pns_unor_id` (`unor_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
